const stations = {
  yerevan: {
    name: "Yerevan",
    country: "Armenia",
    defaultConnectorSize: 100,
    stations: {
      barekamutyun: {
        name: "Barekamutyun",
        name_hy: "Բարեկամություն",
        connector: { color: "red", right: true, station: true, x: 0, y: 0 },
      },
      marshal_baghramyan: {
        name: "Marshal Baghramyan",
        name_hy: "Մարշալ Բաղրամյան",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 100,
          y: 0,
        },
      },
      yeritasardakan: {
        name: "Yeritasardakan",
        name_hy: "Երիտասարդական",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 200,
          y: 0,
        },
      },
      republic_square: {
        name: "Republic Square",
        name_hy: "Հանրապետության հրապարակ",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 300,
          y: 0,
        },
      },
      zoravar_andranik: {
        name: "Zoravar Andranik",
        name_hy: "Զորավար Անդրանիկ",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 400,
          y: 0,
        },
      },
      sasuntsi_davit: {
        name: "Sasuntsi Davit",
        name_hy: "Սասունցի Դավիթ",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 500,
          y: 0,
        },
      },
      gortsaranain: {
        name: "Gortsaranain",
        name_hy: "Գործարանային",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 600,
          y: 0,
        },
      },
      shengavit: {
        name: "Shengavit",
        name_hy: "Շենգավիթ",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          diagonalSE: true,
          x: 700,
          y: 0,
        },
      },
      garegin_nzhdeh: {
        name: "Garegin Nzhdeh",
        name_hy: "Գարեգին Նժդեհ",
        connector: { color: "red", left: true, station: true, x: 900, y: 0 },
      },
      charbakh: {
        name: "Charbakh",
        name_hy: "Չարբախ",
        connector: {
          color: "blue",
          left: true,
          station: true,
          x: 900,
          y: 100,
        },
      },
    },
    extraConnectors: [
      { color: "red", horizontal: true, x: 800, y: 0 },
      { color: "blue", right: true, diagonalNW: true, x: 800, y: 100 },
    ],
  },
  tbilisi: {
    name: "Tbilisi",
    country: "Georgia",
    defaultConnectorSize: 75,
    stations: {
      akhmeteli_theatre: {
        name: "Akhmeteli Theatre",
        name_ka: "ახმეტელის თეატრი",
        connector: { color: "red", right: true, station: true, x: 0, y: 0 },
      },
      sarajishvili: {
        name: "Sarajishvili",
        name_ka: "სარაჯიშვილი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 75,
          y: 0,
        },
      },
      guramishvili: {
        name: "Guramishvili",
        name_ka: "გურამიშვილი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 150,
          y: 0,
        },
      },
      ghrmaghele: {
        name: "Ghrmaghele",
        name_ka: "ღრმაღელე",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 225,
          y: 0,
        },
      },
      didube: {
        name: "Didube",
        name_ka: "დიდუბე",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 300,
          y: 0,
        },
      },
      gotsiridze: {
        name: "Gotsiridze",
        name_ka: "გოცირიძე",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 375,
          y: 0,
        },
      },
      nadzaladevi: {
        name: "Nadzaladevi",
        name_ka: "ნაძალადევი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 450,
          y: 0,
        },
      },
      station_square_1: {
        name: "Station Sq. I",
        name_ka: "სადგურის მოედანი I",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          bottom: true,
          x: 525,
          y: 0,
          labelPlacement: "top-right",
        },
      },
      marjanishvili: {
        name: "Marjanishvili",
        name_ka: "მარჯანიშვილი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 600,
          y: 0,
        },
      },
      rustaveli: {
        name: "Rustaveli",
        name_ka: "რუსთაველი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 675,
          y: 0,
        },
      },
      freedom_square: {
        name: "Freedom Square",
        name_ka: "თავისუფლების მოედანი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 750,
          y: 0,
        },
      },
      avlabari: {
        name: "Avlabari",
        name_ka: "ავლაბარი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 825,
          y: 0,
        },
      },
      aragveli: {
        name: "300 Aragveli",
        name_ka: "300 არაგველი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 900,
          y: 0,
        },
      },
      isani: {
        name: "Isani",
        name_ka: "ისანი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 975,
          y: 0,
        },
      },
      samgori: {
        name: "Samgori",
        name_ka: "სამგორი",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 1050,
          y: 0,
        },
      },
      varketili: {
        name: "Varketili",
        name_ka: "ვარკეთილი",
        connector: {
          color: "red",
          left: true,
          station: true,
          x: 1125,
          y: 0,
        },
      },
      station_square_2: {
        name: "Station Sq. II",
        name_ka: "სადგურის მოედანი II",
        connector: {
          color: "green",
          top: true,
          left: true,
          station: true,
          x: 525,
          y: 75,
          labelPlacement: "bottom-right",
        },
      },
      technical_university: {
        name: "Technical Uni.",
        name_ka: "ტექნიკური უნივერსიტეტი",
        connector: {
          color: "green",
          horizontal: true,
          station: true,
          x: 450,
          y: 75,
          labelPlacement: "bottom-right",
        },
      },
      medical_university: {
        name: "Medical Uni.",
        name_ka: "სამედიცინო უნივერსიტეტი",
        connector: {
          color: "green",
          horizontal: true,
          station: true,
          x: 375,
          y: 75,
          labelPlacement: "bottom-right",
        },
      },
      delisi: {
        name: "Delisi",
        name_ka: "დელისი",
        connector: {
          color: "green",
          horizontal: true,
          station: true,
          x: 300,
          y: 75,
          labelPlacement: "bottom-right",
        },
      },
      vazha_pshavela: {
        name: "Vazha-Pshavela",
        name_ka: "ვაჟა-ფშაველა",
        connector: {
          color: "green",
          horizontal: true,
          station: true,
          x: 225,
          y: 75,
          labelPlacement: "bottom-right",
        },
      },
      state_university: {
        name: "State Uni.",
        name_ka: "უნივერსიტეტი",
        connector: {
          color: "green",
          right: true,
          station: true,
          x: 150,
          y: 75,
          labelPlacement: "bottom-right",
        },
      },
    },
  },
  minsk: {
    name: "Minsk",
    country: "Belarus",
    defaultConnectorSize: 75,
    stations: {
      // Maskoŭskaja line (Blue)
      malinauka: {
        name: "Malinaŭka",
        name_be: "Малінаўка",
        connector: {
          color: "blue",
          right: true,
          station: true,
          x: 0,
          y: 0,
        },
      },
      piatroŭščyna: {
        name: "Piatroŭščyna",
        name_be: "Пятроўшчына",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          x: 75,
          y: 0,
        },
      },
      mihalova: {
        name: "Michałova",
        name_be: "Міхалова",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          x: 150,
          y: 0,
        },
      },
      hrušaŭka: {
        name: "Hrušaŭka",
        name_be: "Грушаўка",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          x: 225,
          y: 0,
        },
      },
      instytut_kultury: {
        name: "Instytut Kultury",
        name_be: "Інстытут Культуры",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          x: 300,
          y: 0,
        },
      },
      plosca_lenina: {
        name: "Plošča Lenina",
        name_be: "Плошча Леніна",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          bottom: true,
          x: 375,
          y: 0,
        },
      },
      kastrycnickaja: {
        name: "Kastryčnickaja",
        name_be: "Кастрычніцкая",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          bottom: true,
          x: 450,
          y: 0,
        },
      },
      plosca_pieramohi: {
        name: "Plošča Pieramohi",
        name_be: "Плошча Перамогі",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          x: 525,
          y: 0,
        },
      },
      akademija_navuk: {
        name: "Akademija Navuk",
        name_be: "Акадэмія Навук",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          x: 600,
          y: 0,
        },
      },
      park_caliuskincau: {
        name: "Park Čaliuskincaŭ",
        name_be: "Парк Чалюскінцаў",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          x: 675,
          y: 0,
        },
      },
      maskoŭskaja: {
        name: "Maskoŭskaja",
        name_be: "Маскоўская",
        connector: {
          color: "blue",
          horizontal: true,
          station: true,
          x: 750,
          y: 0,
        },
      },
      uschod: {
        name: "Uchod",
        name_be: "Усход",
        connector: {
          color: "blue",
          left: true,
          station: true,
          x: 825,
          y: 0,
        },
      },

      // Aŭtazavodskaja line (Red)
      mahilioŭskaja: {
        name: "Mahilioŭskaja",
        name_be: "Магілёўская",
        connector: {
          color: "red",
          right: true,
          station: true,
          x: 0,
          y: 75,
        },
      },
      aŭtazavodskaja: {
        name: "Aŭtazavodskaja",
        name_be: "Аўтазаводская",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 75,
          y: 75,
        },
      },
      partyzanskaja: {
        name: "Partyzanskaja",
        name_be: "Партызанская",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 150,
          y: 75,
        },
      },
      traktarny_zavod: {
        name: "Traktarny Zavod",
        name_be: "Трактарны Завод",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 225,
          y: 75,
        },
      },
      praletarskaja: {
        name: "Praletarskaja",
        name_be: "Пралетарская",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 300,
          y: 75,
        },
      },
      pieršamajskaja: {
        name: "Pieršamajskaja",
        name_be: "Першамайская",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 375,
          y: 75,
        },
      },
      kupalaŭskaja: {
        name: "Kupalaŭskaja",
        name_be: "Купалаўская",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          top: true,
          x: 450,
          y: 75,
        },
      },
      niamiga: {
        name: "Niamiga",
        name_be: "Няміга",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 525,
          y: 75,
        },
      },
      frunzienskaja: {
        name: "Frunzienskaja",
        name_be: "Фрунзенская",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          bottom: true,
          x: 600,
          y: 75,
        },
      },
      maladziožnaja: {
        name: "Maladziožnaja",
        name_be: "Маладзёжная",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 675,
          y: 75,
        },
      },
      puškinskaja: {
        name: "Puškinskaja",
        name_be: "Пушкінская",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 750,
          y: 75,
        },
      },
      spartyŭnaja: {
        name: "Spartyŭnaja",
        name_be: "Спартыўная",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 825,
          y: 75,
        },
      },
      kunčaŭščyna: {
        name: "Kunčaŭščyna",
        name_be: "Кунцаўшчына",
        connector: {
          color: "red",
          horizontal: true,
          station: true,
          x: 900,
          y: 75,
        },
      },
      kamiennaja_horka: {
        name: "Kamiennaja Horka",
        name_be: "Каменная Горка",
        connector: {
          color: "red",
          left: true,
          station: true,
          x: 975,
          y: 75,
        },
      },

      /// Zelenalužskaja line (Green)
      jubilejnaja_plosca: {
        name: "Jubilejnaja Plošča",
        name_be: "Юбілейная Плошча",
        connector: {
          color: "green",
          left: true,
          top: true,
          station: true,
          x: 600,
          y: 150,
          labelPlacement: "bottom-right",
        },
      },
      plosca_franciška_bahuševiča: {
        name: "Plošča Franciška Bahuševiča",
        name_be: "Плошча Францішка Багушэвіча",
        connector: {
          color: "green",
          horizontal: true,
          station: true,
          x: 525,
          y: 150,
          labelPlacement: "bottom-right",
        },
      },
      vakzalnaja: {
        name: "Vakzalnaja",
        name_be: "Вакзальная",
        connector: {
          color: "green",
          horizontal: true,
          station: true,
          x: 450,
          y: 150,
          labelPlacement: "bottom-right",
        },
      },
      kavalskaja_slobada: {
        name: "Kavaĺskaja Slobada",
        name_be: "Кавальская Слабада",
        connector: {
          color: "green",
          right: true,
          station: true,
          x: 375,
          y: 150,
          labelPlacement: "bottom-right",
        },
      },
    },
    extraConnectors: [
      { color: "green", horizontal: true, x: 450, y: 150, diagonalNW: true },
      { color: "green", x: 375, y: 75, top: true, diagonalSE: true },
    ],
  },
};

export default stations;
